[package]
name = "RustLibrary"
version = "0.1.1"
authors = ["Sumeru Chatterjee <sumeru.chatterjee@me.com"]
description = "Example static library project built for iOS"
publish = false

[lib]
name = "RustLibrary"
crate-type = ["staticlib", "cdylib"]
